config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'
  
  namespace :api do
    resources :todos, defaults: { format: :json }, except: [:new, :edit] do
      resources :steps, only: [:create]
      resources :tags, only: [:create]
    end

    resources :steps, defaults: { format: :json }, only: [:update, :destroy, :index]
  end

  resources :taggings, only: [:create]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/step.rb
class Step < ApplicationRecord
  validates :todo_id, :body, presence: true
  validates :done, inclusion: { in: [true, false] }

  belongs_to :todo
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :taggings, dependent: :destroy
  has_many :todos, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  validates :todo_id, presence: true, uniqueness: { scope: :tag_id }
  validates :tag_id, presence: true

  belongs_to :tag
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :done, inclusion: { in: [true, false] }

  belongs_to :user

  has_many :steps, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_names=(tag_names)
    self.tags = tag_names.map do |tag_name|
      Tag.find_or_create_by(name: tag_name)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true

  after_initialize :ensure_session_token

  has_many :todos, dependent: :destroy

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(user_params)
    user = User.find_by(username: user_params[:username])
    return nil if user.nil?
    user.is_password?(user_params[:password]) ? user : nil
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    save!
    session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/api/steps_controller.rb
class Api::StepsController < ApplicationController
  def index
    render json: Step.all
  end

  def create
    @step = Step.new(step_params)
    @step.todo_id = params[:todo_id]

    if @step.save
      render json: @step
    else
      render json: @step.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    @step = Step.find(params[:id])

    if @step.update_attributes(step_params)
      render json: @step
    else
      render json: @step.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @step = Step.find(params[:id])
    @step.destroy
    render json: @step
  end


  private

  def step_params
    params.require(:step).permit(:body, :done)
  end
end

app/controllers/api/tags_controller.rb
class Api::TagsController < ApplicationController
  def create
    #TODO find_or_create_by, move logic to taggings controller
    @tag = Tag.find_or_create_by(name: tag_params['name'])
    @todo = Todo.find(params[:todo_id])

    if @todo.tags.include?(@tag)
      render json: ["Todo is already tagged with '#{@tag.name}'"], status: :precondition_failed
    else
      tagging = Tagging.create(todo_id: params[:todo_id], tag_id: @tag.id)
      render json: @tag
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/api/todos_controller.rb
class Api::TodosController < ApplicationController
  before_action :redirect_if_not_logged_in

  def show
    @todo = Todo.find(params[:id])

    if @todo.user_id == current_user.id
      @todo
    else
      render json: 'access forbidden', status: :forbidden
    end
  end

  def index
    @todos = current_user.todos
  end

  def create
    @todo = current_user.todos.new(todo_params)

    if @todo.save
      render json: @todo, include: :tags
    else
      render json: @todo.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    @todo = current_user.todos.find(params[:id])

    if @todo.update_attributes(todo_params)
      render json: @todo, include: :tags
    else
      render json: @todo.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = current_user.todos.find(params[:id])
    @todo.destroy
    render json: @todo
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :body, :done, :due_date, tag_names: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?
  helper_method :logged_out?

  private
  def logged_in?
    current_user
  end

  def logged_out?
    !logged_in?
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def redirect_if_logged_in
    redirect_to root_url if logged_in?
  end

  def redirect_if_not_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, except: [:destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      user_params
    )

    if @user.nil?
      @user = User.new
      flash.now[:danger] = ['Invalid username and/or password']
      render :new
    else
      login!(@user)
      redirect_to root_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_if_not_logged_in

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:danger] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/api/todos_controller_helper.rb
module Api::TodosControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>dos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/x-icon' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'todo_redux' %>
    <%= stylesheet_pack_tag 'todo_redux' %>
  </head>

  <body class="container-fluid">
    <%= render 'partials/header' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<header class="row justify-content-between mt-2 border-bottom">
  <h1 class="col-6 text-success">2 dos</h1>
  <div class="col-2 justify-content-end <%= logged_out? ? 'd-none' : 'd-flex' %>">
    <form class="align-self-center" method="post" action="/session">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
      <input name="_method" type="hidden" value="DELETE">
      <button class="btn btn-outline-dark">Logout</button>
    </form>
  </div>
</header>

app/views/partials/_sign_in_up.html.erb
<% flash.each do |key, value| %>
  <ul class="col-12 alert alert-<%= key %>">
  <% flash[key].each do |error_msg| %>
    <li ><%= error_msg %></li>
  <% end %>
  </ul>
<% end %>
<form method="post" action="/<%= action %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <label for="username-input">Username</label>
  <div class="form-group">
    <input type="text" class="form-control" id="username-input"
          placeholder="<%= Faker::LordOfTheRings.character.split(' ').map(&:capitalize).join('') %>"
          value="<%= @user.username %>" name="user[username]"
    />
  </div>
  <div class="form-group">
    <label for="password-input">Password</label>
    <input type="password" class="form-control" is="password-input"
          value="<%= @user.password %>" name="user[password]"
    />
  </div>
  <div class="d-flex">
    <button class="btn btn-primary mr-2"><%= action === 'session' ? 'Log In' : 'Sign Up' %></button>
    <a class="btn btn-outline-primary" href="<%= action === 'session' ? new_user_url : new_session_url %>">
      <%= action === 'session' ? 'Sign up' : 'Log in' %> Instead
    </a>
  </div>
</form>

app/views/static_pages/root.html.erb
<div id="root">

</div>

app/views/users/new.html.erb
<%= render 'partials/sign_in_up', action: 'users' %>